name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install root dependencies
      run: npm install

    - name: Install server dependencies
      run: npm install --prefix server

    - name: Install client dependencies
      run: npm install --prefix client

    - name: Build client
      run: npm run build --prefix client

    # - name: Run server tests
    #   run: npm test --prefix server

    # - name: Run client tests
    #   run: npm test --prefix client

  # deploy:
  #   name: Deploy to AWS
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #
  #   - name: Configure AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v2
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: YOUR_AWS_REGION # e.g., us-east-1
  #
  #   # Add your deployment steps here. For example:
  #   # - Build and push a Docker image to Amazon ECR
  #   # - Deploy to Amazon ECS, AWS Elastic Beanstalk, or an S3 bucket
  #   - name: Deploy to S3
  #     run: |
  #       # Example command to sync the client build to an S3 bucket
  #       aws s3 sync client/dist s3://your-s3-bucket-name 